refactored model tests
mblopes/learn_tdd pull request #1
Opened 2021-01-29 20:54 UTC by lucianahb

2021-01-29 21:09 UTC, josue-avila requested changes

2021-01-29 21:09 UTC, josue-avila commented on .vscode/settings.json
> +}
É legal adicionar essa pasta .vscode no .gitignore pra não subir mais

2021-01-29 21:09 UTC, josue-avila commented on models/category_model.py
> +# from sqlalchemy.orm import validates
Dá pra excluir essa linha aqui

2021-01-29 21:09 UTC, josue-avila commented on tests/test_category_model.py
> +    ])
Dá pra usar o @pytest.mark.parametrize só pra 'name' pra não repetir a descrição três vezes. Segue exemplo:

    @pytest.mark.parametrize("name", [
        None, 5, 5.0, [1, 2, 3],
        ('a', 'b', 'c'),
        Category('name', 'description'),
        {'name': 'test name',
         'description': 'test description'}
    ])
    def test_name_not_instance_str(self, name):
        with pytest.raises(TypeError):
            Category(name, 'test description')
            
E isso pode ser replicado para description (invertendo é claro XP)

2021-02-01 11:44 UTC, mblopes approved these changes

2021-02-01 12:01 UTC, josue-avila approved these changes

2021-02-01 12:03 UTC, merged